debug: false
serverintervalminutes: 1
hec:
  eanbled: false
scanfiles:
  - path: ./test.single
    comment: testfile normal
  - path: ./test.single
    comment: testfile with subtractdays
    substractvaliditydays: 100
scantlsexpiry:
  - connect: www.google.com:443
    substractvaliditydays: 9
out:
  warnafterdays: 60
  warnexitcodes: true
  infoafterdays: 67
  infoexitcodes: false
  debugafterdays: 70
  debugexitcodes: true
